# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d083521c7f9235671db0c5c51456a70052070c71a5ce6a2d035521bd94b5923a834a257048005b81ef519b7a723b32a30eded9ee5cbd4077b614c71a00b7883b

test:
  secret_key_base: 82852c94b46285e34d451e88ce9fa3be8cd80f8bd294784a12dfd97659dd57138088e850e8c5719f0c6bf877c7f22d7fe006791ed1ea73ad68ca91eb1321f9a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
